- name: return ls from root
  hosts: all
  vars:
    directory: /

  tasks:

    - command: "ls {{directory}}"
      register: dir_out

    - debug: var={{item}}
      with_items: dir_out.stdout_lines
    
